### ISSUE TITLE
waiter screen doesn't update if not logged in

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/SynapseShinyApp#17]
#15/#16 don't seem to work when an app is deployed to the shiny server, though they do work locally.

Locally, there is no session token cookie, and attempting to log in without providing credentials through the .synapseConfig throws an error, which prompts the waiter message to update and instruct the user to log in. This does not happen when the app is deployed to the shiny server, I'm guessing because `input$cookie` is never modified because there is no cookie, so the `observeEvent()` is not triggered. When I deploy this sample app as-is, if I'm not logged in to Synapse I see the "Retrieving Synapse information..." screen indefinitely.

**Comment by thomasyu888** [comment]
@vpchung, I seem to remember you got this working on the shiny server.  Did you run into this issue?

**Comment by vpchung** [comment]
Hmm, I did not. I am also not experiencing the same error as @karawoo after creating a sample app. Maybe it's been fixed...?

**Comment by karawoo** [comment]
Interesting. @vpchung when you visit [this one](https://shinypro.synapse.org/users/kwoo/SynapseShinyApp/) while not logged in to Synapse, do you see the prompt telling you to log in? I do not -- I get "Retrieving Synapse information..." indefinitely (at least several full minutes). I know @Aryllen has seen this as well with other apps. The sample app I linked is using the reticulate branch, but I see the same behavior if I deploy the version that uses synapser.

**Comment by vpchung** [comment]
That's weird... I do get the indefinite loading screen there. Can you see if you experience the same with [my copy](https://shinypro.synapse.org/users/vchung/SynapseShinyApp/) of the app?

**Comment by karawoo** [comment]
VERY weird. I get the "Looks like you're not logged in!" message on your copy.

**Comment by vpchung** [comment]
..... so I just tried switching to the `reticulate` branch and back, and now my app is also not behaving expectedly anymore.

wot
