### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseShinyApp#2]
![screen shot 2015-12-03 at 9 28 49 pm](https://cloud.githubusercontent.com/assets/10556275/11582535/f00c1dce-9a04-11e5-8022-d8af50bc2b30.png)

**Comment by kdaily** [comment]
Weird. Looking into it. I must have authenticated once somehow (successfully) and it was cached?

**Comment by kdaily** [comment]
Duh. Only works on staging right now.

**Comment by thomasyu888** [comment]
Just tried on staging.  It doesn't work. =/

**Comment by thomasyu888** [comment]
Just tried on staging.  It doesn't work. =/
![screen shot 2015-12-04 at 4 53 13 pm](https://cloud.githubusercontent.com/assets/10556275/11604887/9ad0e74c-9aa7-11e5-9c28-caa656845400.png)

**Comment by kdaily** [comment]
Need to switch to staging endpoints in the app (before logging in with
`synSetEndpoints`).

**Comment by thomasyu888** [comment]
Ahh! Thanks!

**Comment by kdaily** [comment]
It's broken, missing a crucial component to bind the output of `readCookie` to a shiny object.
